# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ethan/chess-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ethan/chess-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ethan/chess-project/CMakeFiles /home/ethan/chess-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ethan/chess-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess_project

# Build rule for target.
chess_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chess_project
.PHONY : chess_project

# fast build rule for target.
chess_project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/build
.PHONY : chess_project/fast

src/controller/controller.o: src/controller/controller.cpp.o
.PHONY : src/controller/controller.o

# target to build an object file
src/controller/controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/controller/controller.cpp.o
.PHONY : src/controller/controller.cpp.o

src/controller/controller.i: src/controller/controller.cpp.i
.PHONY : src/controller/controller.i

# target to preprocess a source file
src/controller/controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/controller/controller.cpp.i
.PHONY : src/controller/controller.cpp.i

src/controller/controller.s: src/controller/controller.cpp.s
.PHONY : src/controller/controller.s

# target to generate assembly for a file
src/controller/controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/controller/controller.cpp.s
.PHONY : src/controller/controller.cpp.s

src/logic/chessboard.o: src/logic/chessboard.cpp.o
.PHONY : src/logic/chessboard.o

# target to build an object file
src/logic/chessboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/logic/chessboard.cpp.o
.PHONY : src/logic/chessboard.cpp.o

src/logic/chessboard.i: src/logic/chessboard.cpp.i
.PHONY : src/logic/chessboard.i

# target to preprocess a source file
src/logic/chessboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/logic/chessboard.cpp.i
.PHONY : src/logic/chessboard.cpp.i

src/logic/chessboard.s: src/logic/chessboard.cpp.s
.PHONY : src/logic/chessboard.s

# target to generate assembly for a file
src/logic/chessboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/logic/chessboard.cpp.s
.PHONY : src/logic/chessboard.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/player/tui.o: src/player/tui.cpp.o
.PHONY : src/player/tui.o

# target to build an object file
src/player/tui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/player/tui.cpp.o
.PHONY : src/player/tui.cpp.o

src/player/tui.i: src/player/tui.cpp.i
.PHONY : src/player/tui.i

# target to preprocess a source file
src/player/tui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/player/tui.cpp.i
.PHONY : src/player/tui.cpp.i

src/player/tui.s: src/player/tui.cpp.s
.PHONY : src/player/tui.s

# target to generate assembly for a file
src/player/tui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/player/tui.cpp.s
.PHONY : src/player/tui.cpp.s

src/view/tui.o: src/view/tui.cpp.o
.PHONY : src/view/tui.o

# target to build an object file
src/view/tui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/view/tui.cpp.o
.PHONY : src/view/tui.cpp.o

src/view/tui.i: src/view/tui.cpp.i
.PHONY : src/view/tui.i

# target to preprocess a source file
src/view/tui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/view/tui.cpp.i
.PHONY : src/view/tui.cpp.i

src/view/tui.s: src/view/tui.cpp.s
.PHONY : src/view/tui.s

# target to generate assembly for a file
src/view/tui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_project.dir/build.make CMakeFiles/chess_project.dir/src/view/tui.cpp.s
.PHONY : src/view/tui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chess_project"
	@echo "... src/controller/controller.o"
	@echo "... src/controller/controller.i"
	@echo "... src/controller/controller.s"
	@echo "... src/logic/chessboard.o"
	@echo "... src/logic/chessboard.i"
	@echo "... src/logic/chessboard.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/player/tui.o"
	@echo "... src/player/tui.i"
	@echo "... src/player/tui.s"
	@echo "... src/view/tui.o"
	@echo "... src/view/tui.i"
	@echo "... src/view/tui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

