enum Move : int {
	MOVE_NONE,
	MOVE_NULL = 65,
};

enum MoveType {
	NORMAL,
	PROMOTION = 1 << 14,
	EN_PASSANT = 2 << 14,
	CASTLING = 3 << 14,
};

enum Color {
	WHITE,
	BLACK,
	COLOR_NB = 2,
};

enum CastlingRights {
	NO_CASTLING,
	WHITE_OO,
	WHITE_OOO = WHITE_OO << 1,
	BLACK_OO  = WHITE_OO << 2,
	BLACK_OOO = WHITE_OO << 3,

	KING_SIDE      = WHITE_OO  | BLACK_OO,
	QUEEN_SIDE     = WHITE_OOO | BLACK_OOO,
	WHITE_CASTLING = WHITE_OO  | WHITE_OOO,
	BLACK_CASTLING = BLACK_OO  | BLACK_OOO,
	ANY_CASTLING   = WHITE_CASTLING | BLACK_CASTLING,

	CASTLING_RIGHT_NB = 16
};

enum PieceType {
	NO_PIECE_TYPE,
	PAWN,
	KNIGHT,
	BISHOP,
	ROOK,
	QUEEN,
	KING,

	ALL_PIECES = 0,
	PIECE_TYPE_NB = 8
};

enum Square : int {
	SQ_A1, SQ_B1, SQ_C1, SQ_D1, SQ_E1, SQ_F1, SQ_G1, SQ_H1,
	SQ_A2, SQ_B2, SQ_C2, SQ_D2, SQ_E2, SQ_F2, SQ_G2, SQ_H2,
	SQ_A3, SQ_B3, SQ_C3, SQ_D3, SQ_E3, SQ_F3, SQ_G3, SQ_H3,
	SQ_A4, SQ_B4, SQ_C4, SQ_D4, SQ_E4, SQ_F4, SQ_G4, SQ_H4,
	SQ_A5, SQ_B5, SQ_C5, SQ_D5, SQ_E5, SQ_F5, SQ_G5, SQ_H5,
	SQ_A6, SQ_B6, SQ_C6, SQ_D6, SQ_E6, SQ_F6, SQ_G6, SQ_H6,
	SQ_A7, SQ_B7, SQ_C7, SQ_D7, SQ_E7, SQ_F7, SQ_G7, SQ_H7,
	SQ_A8, SQ_B8, SQ_C8, SQ_D8, SQ_E8, SQ_F8, SQ_G8, SQ_H8,
	SQ_NONE,

	SQUARE_NB   = 64
};

enum Direction : int {
	NORTH =  8,
	EAST  =  1,
	SOUTH = -NORTH,
	WEST  = -EAST,

	NORTH_EAST = NORTH + EAST,
	SOUTH_EAST = SOUTH + EAST,
	SOUTH_WEST = SOUTH + WEST,
	NORTH_WEST = NORTH + WEST
};
